title: Atanu Dutta
logo: /assets/img/Atanu Dutta Badge Pic blue.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/atanudutta/">LinkedIn</a> |
  <a href="https://github.com/atanudutta-git">GitHub</a>

  <br>   
  I'm working as Sr Manager Marketing Analytics
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
